name: 'Sync wiki to a branch'
description: 'Synchronize wiki updates with a branch in the repository'
inputs:
  branch:
    description: 'The name of the repository branch that should track the wiki'
    default: 'wiki'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.branch }}